site_name: Metrics Toolkit
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
  palette:
    primary: blue grey
    accent: blue
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/metrics_toolkit
      name: Metrics Toolkit on Twitter
language: en
font:
  text: Roboto
  code: Roboto Mono
plugins:
  - search
markdown_extensions:
  - meta
docs_dir: docs
nav:
  - Home: index.md
  - Browse Metrics:
    - Altmetric Attention Score: /metrics/altmetricattention.md
    - Eigenfactor Score & Article Influence Score: /metrics/eigenfactor.md
    - Facebook Posts, Comments, Likes, & Shares: /metrics/facebook.md
    - Github Forks, Collaborators, & Watchers: /metrics/github.md
    - H-Index: /metrics/hindex.md
    - Journal Acceptance Rate: /metrics/journalacceptance.md
    - Journal Impact Factor: /metrics/journalimpactfactor.md
    - Monograph Holdings: /metrics/monographholdings.md
    - Monograph Sales & Rankings: /metrics/monographsales.md
    - Policy Citations: /metrics/policycitations.md
    - Relative Citation Ratio (RCR): /metrics/relativecitationratio.md
    - Twitter mentions: /metrics/twittermentions.md
    - Wikipedia Citations: /metrics/wikipedia.md
  - About:
    - mt_mission.md
    - Schema:
      - Metrics Toolkit Schema V2: mt_schema_v2.md
      - Metrics Toolkit Schema V1: mt_schema_v1.md
    - Editorial Boad:
      - editorial_board.md
