site_name: Metrics Toolkit
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
  palette:
    primary: blue grey
    accent: blue
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/metrics_toolkit
      name: Metrics Toolkit on Twitter
language: en
font:
  text: Roboto
  code: Roboto Mono
plugins:
  - search
markdown_extensions:
  - meta
docs_dir: docs
nav:
  - Home: index.md
  - How to: how_to.md
  - Browse Metrics:
    - Altmetric Attention Score: altmetricattention.md
    - Eigenfactor Score & Article Influence Score: eigenfactor.md
    - Facebook Posts, Comments, Likes, & Shares: facebook.md
    - Github Forks, Collaborators, & Watchers: github.md
    - H-Index: hindex.md
    - Journal Acceptance Rate: journalacceptance.md
    - Journal Impact Factor: journalimpactfactor.md
    - Monograph Holdings: monographholdings.md
    - Monograph Sales & Rankings: monographsales.md
    - Policy Citations: policycitations.md
    - Relative Citation Ratio (RCR): relativecitationratio.md
    - Twitter mentions: twittermentions.md
    - Wikipedia Citations: wikipedia.md
  - About:
    - Schema:
      - Metrics Toolkit Schema V2: mt_schema_v2.md
      - Metrics Toolkit Schema V1: mt_schema_v1.md
    - Editorial Board:
      - editorial_board.md
