site_name: Metrics Toolkit
theme: material
plugins:
  - search
docs_dir: docs
nav:
  - Home: index.md
  - Browse Metrics:
    - Altmetric Score: lesson1.md
    - H-Index: lesson4.md
  - Resources: lesson2.md
  - About: lesson3.md
  - Glossary: glossary.md
