site_name: Metrics Toolkit
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
  palette:
    primary: blue grey
    accent: blue
language: en
font:
  text: Roboto
  code: Roboto Mono
plugins:
  - search
markdown_extensions:
  - meta
docs_dir: docs
nav:
  - Home: index.md
  - Browse Metrics:
    - Altmetric Attention Score: altmetricattention.md
    - Eigenfactor Score & Article Influence Score: eigenfactor.md
    - Facebook Posts, Comments, Likes, & Shares: facebook.md
    - Github Forks, Collaborators, & Watchers: github.md
    - H-Index: hindex.md
    - Journal Acceptance Rate: journalacceptance.md
    - Journal Impact Factor: journalimpactfactor.md
    - Monograph Holdings: monographholdings.md
    - Monograph Sales & Rankings: monographsales.md
    - Policy Citations: policycitations.md
    - Relative Citation Ratio (RCR): relativecitationratio.md
    - Twitter mentions: twittermentions.md
    - Wikipedia Citations: wikipedia.md
  - Schema: mt-schema.md
