site_name: Metrics Toolkit
theme:
  name: null
  custom_dir: mkdocs-material/material
  # 404 page
  static_templates:
    - 404.html
  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true
  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
plugins:
  - search
docs_dir: docs
nav:
  - Home: index.md
  - Browse Metrics:
    - Altmetric Attention Score: altmetricattention.md
    - Eigenfactor Score & Article Influence Score: eigenfactor.md
    - Facebook Posts, Comments, Likes, & Shares: facebook.md
    - Github Forks, Collaborators, & Watchers: github.md
    - H-Index: hindex.md
    - Journal Acceptance Rate: journalacceptance.md
    - Journal Impact Factor: journalimpactfactor.md
    - Monograph Holdings: monographholdings.md
    - Monograph Sales & Rankings: monographsales.md
    - Policy Citations: policycitations.md
    - Relative Citation Ratio (RCR): relativecitationratio.md
    - Twitter mentions: twittermentions.md
    - Wikipedia Citations: wikipedia.md
  - Metrics by Output Type:
  - Metrics by Impact Type:
  - Glossary: glossary.md
  - Schema: mt-schema.md
