site_name: Metrics Toolkit
theme: material
plugins:
  - search
docs_dir: docs
pages:
  - Home: index.md
  - Browse Metrics: lesson1.md
    - Test1: lesson2.md
    - Test2: lesson3.md
  - Resources: lesson2.md
  - About: lesson3.md
  - Glossary: glossary.md
