site_name: Metrics Toolkit
theme: material
plugins:
  - search
docs_dir: docs
nav:
  - Home: index.md
  - Browse Metrics:
    - Altmetric Attention Score: altmetricattention.md
    - Eigenfactor Score & Article Influence Score: eigenfactor.md
    - Github Forks & Collaborators: github.md
    - H-Index: hindex.md
    - Journal Acceptance Rate: journalacceptance.md
    - Monograph Holdings: monographholdings.md
    - Monograph Sales & Rankings: monographsales.md
    - Policy Citations: policycitations.md
    - Relative Citation Ratio (RCR): relativecitationratio.md
    - Wikipedia Citations: wikipedia.md
  - Metrics by Output Type:
    - Articles: lesson2.md
    - Data: lesson2.md
    - Code: lesson2.md
    - Books and Book chapters: lesson2.md
  - Metrics by Impact Type:
    - Type 1: lesson2.md
    - Type 2: lesson2.md
  - Resources: lesson2.md
  - About: lesson3.md
  - Glossary: glossary.md
